# Generated by Django 4.2.3 on 2023-07-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('institutions', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('early_life_education', models.TextField(blank=True, null=True)),
                ('family_career', models.TextField(blank=True, null=True)),
                ('field_work', models.TextField(blank=True, null=True)),
                ('award_honors', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
