# Generated by Django 4.2.3 on 2023-07-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture_3_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
