# Generated by Django 4.2.3 on 2023-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_options_profile_picture_1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_2',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_3',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
